-- ============================================================
-- InvenTrack Pro — Oracle Database Schema
-- Complete normalized schema with indexes, constraints, FK
-- ============================================================

-- ── Roles ──────────────────────────────────────────────────
CREATE TABLE ROLES (
    ROLE_ID         VARCHAR2(36)   PRIMARY KEY,
    NAME            VARCHAR2(50)   NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(300),
    PERMISSIONS     CLOB
);

-- ── Users ──────────────────────────────────────────────────
CREATE TABLE USERS (
    USER_ID                 VARCHAR2(36)   PRIMARY KEY,
    FULL_NAME               VARCHAR2(100)  NOT NULL,
    EMAIL                   VARCHAR2(150)  NOT NULL UNIQUE,
    PASSWORD_HASH           VARCHAR2(255)  NOT NULL,
    ROLE                    VARCHAR2(20)   DEFAULT 'MANAGER'
                            CHECK(ROLE IN ('ADMIN','MANAGER')),
    PHONE                   VARCHAR2(20),
    IS_ACTIVE               NUMBER(1)      DEFAULT 1 NOT NULL,
    WAREHOUSE_ID            VARCHAR2(36),
    LAST_LOGIN              DATE,
    RESET_TOKEN             VARCHAR2(255),
    RESET_TOKEN_EXPIRY      DATE,
    FAILED_LOGIN_ATTEMPTS   NUMBER         DEFAULT 0,
    LOCKED_UNTIL            DATE,
    CREATED_AT              DATE           DEFAULT SYSDATE,
    UPDATED_AT              DATE           DEFAULT SYSDATE
);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);

-- ── Refresh Tokens ─────────────────────────────────────────
CREATE TABLE REFRESH_TOKENS (
    TOKEN_ID        VARCHAR2(36)   PRIMARY KEY,
    USER_ID         VARCHAR2(36)   NOT NULL,
    TOKEN           VARCHAR2(500)  NOT NULL UNIQUE,
    TOKEN_FAMILY    VARCHAR2(36)   NOT NULL,
    EXPIRES_AT      DATE           NOT NULL,
    IS_REVOKED      NUMBER(1)      DEFAULT 0,
    CREATED_AT      DATE           DEFAULT SYSDATE,
    CONSTRAINT FK_RT_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_RT_USER_ID ON REFRESH_TOKENS(USER_ID);
CREATE INDEX IDX_RT_TOKEN_FAMILY ON REFRESH_TOKENS(TOKEN_FAMILY);

-- ── Warehouses ─────────────────────────────────────────────
CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID        VARCHAR2(36)    PRIMARY KEY,
    NAME                VARCHAR2(150)   NOT NULL,
    ADDRESS             VARCHAR2(300)   NOT NULL,
    CITY                VARCHAR2(100)   NOT NULL,
    STATE               VARCHAR2(100)   NOT NULL,
    COUNTRY             VARCHAR2(100)   NOT NULL,
    PIN_CODE            VARCHAR2(20),
    CONTACT_PERSON      VARCHAR2(100)   NOT NULL,
    CONTACT_PHONE       VARCHAR2(20)    NOT NULL,
    CONTACT_EMAIL       VARCHAR2(150),
    CAPACITY            NUMBER          NOT NULL CHECK(CAPACITY > 0),
    CURRENT_STOCK_COUNT NUMBER          DEFAULT 0,
    IS_ACTIVE           NUMBER(1)       DEFAULT 1,
    CREATED_AT          DATE            DEFAULT SYSDATE,
    UPDATED_AT          DATE            DEFAULT SYSDATE
);
CREATE INDEX IDX_WH_CITY ON WAREHOUSES(CITY);
CREATE INDEX IDX_WH_ACTIVE ON WAREHOUSES(IS_ACTIVE);

-- ── Suppliers ──────────────────────────────────────────────
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID         VARCHAR2(36)    PRIMARY KEY,
    NAME                VARCHAR2(150)   NOT NULL,
    CONTACT_PERSON      VARCHAR2(100)   NOT NULL,
    PHONE               VARCHAR2(20)    NOT NULL,
    EMAIL               VARCHAR2(150)   NOT NULL,
    ADDRESS             VARCHAR2(300)   NOT NULL,
    CITY                VARCHAR2(100)   NOT NULL,
    STATE               VARCHAR2(100)   NOT NULL,
    COUNTRY             VARCHAR2(100)   NOT NULL,
    GST_NUMBER          VARCHAR2(20),
    LEAD_TIME_DAYS      NUMBER          DEFAULT 7,
    PAYMENT_TERMS       VARCHAR2(200),
    RATING              NUMBER(3,1)     DEFAULT 0 CHECK(RATING BETWEEN 0 AND 5),
    TOTAL_ORDERS        NUMBER          DEFAULT 0,
    ON_TIME_DELIVERIES  NUMBER          DEFAULT 0,
    NOTES               VARCHAR2(500),
    IS_ACTIVE           NUMBER(1)       DEFAULT 1,
    CREATED_AT          DATE            DEFAULT SYSDATE,
    UPDATED_AT          DATE            DEFAULT SYSDATE
);
CREATE INDEX IDX_SUP_NAME ON SUPPLIERS(LOWER(NAME));
CREATE INDEX IDX_SUP_ACTIVE ON SUPPLIERS(IS_ACTIVE);

-- ── Products ───────────────────────────────────────────────
CREATE TABLE PRODUCTS (
    PRODUCT_ID      VARCHAR2(36)    PRIMARY KEY,
    SKU             VARCHAR2(100)   NOT NULL UNIQUE,
    NAME            VARCHAR2(200)   NOT NULL,
    CATEGORY        VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    UNIT_PRICE      NUMBER(14,2)    NOT NULL CHECK(UNIT_PRICE >= 0),
    QUANTITY        NUMBER          DEFAULT 0 CHECK(QUANTITY >= 0),
    MIN_STOCK_LEVEL NUMBER          DEFAULT 10,
    MAX_STOCK_LEVEL NUMBER          DEFAULT 1000,
    REORDER_POINT   NUMBER          DEFAULT 20,
    UNIT_OF_MEASURE VARCHAR2(50)    DEFAULT 'UNIT',
    WEIGHT          NUMBER,
    DIMENSIONS      VARCHAR2(100),
    BARCODE         VARCHAR2(255),
    BARCODE_TYPE    VARCHAR2(20)    DEFAULT 'CODE128',
    WAREHOUSE_ID    VARCHAR2(36),
    SUPPLIER_ID     VARCHAR2(36),
    IS_ACTIVE       NUMBER(1)       DEFAULT 1,
    CREATED_AT      DATE            DEFAULT SYSDATE,
    UPDATED_AT      DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_PROD_WH FOREIGN KEY(WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT FK_PROD_SUP FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);
CREATE INDEX IDX_PROD_SKU ON PRODUCTS(SKU);
CREATE INDEX IDX_PROD_BARCODE ON PRODUCTS(BARCODE);
CREATE INDEX IDX_PROD_CATEGORY ON PRODUCTS(CATEGORY);
CREATE INDEX IDX_PROD_WH ON PRODUCTS(WAREHOUSE_ID);
CREATE INDEX IDX_PROD_ACTIVE ON PRODUCTS(IS_ACTIVE);
CREATE INDEX IDX_PROD_STOCK ON PRODUCTS(QUANTITY, MIN_STOCK_LEVEL);

-- ── Inventory ──────────────────────────────────────────────
CREATE TABLE INVENTORY (
    INVENTORY_ID        VARCHAR2(36)    PRIMARY KEY,
    PRODUCT_ID          VARCHAR2(36)    NOT NULL,
    WAREHOUSE_ID        VARCHAR2(36)    NOT NULL,
    QUANTITY_ON_HAND    NUMBER          DEFAULT 0,
    QUANTITY_RESERVED   NUMBER          DEFAULT 0,
    QUANTITY_AVAILABLE  NUMBER          DEFAULT 0,
    LAST_AUDIT_DATE     DATE,
    LAST_COUNT_QUANTITY NUMBER,
    AVERAGE_COST        NUMBER(14,2)    DEFAULT 0,
    TOTAL_VALUE         NUMBER(14,2)    DEFAULT 0,
    CREATED_AT          DATE            DEFAULT SYSDATE,
    UPDATED_AT          DATE,
    CONSTRAINT FK_INV_PROD FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_INV_WH FOREIGN KEY(WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT UQ_INV_PROD_WH UNIQUE(PRODUCT_ID, WAREHOUSE_ID)
);
CREATE INDEX IDX_INV_PROD ON INVENTORY(PRODUCT_ID);
CREATE INDEX IDX_INV_WH ON INVENTORY(WAREHOUSE_ID);

-- ── Purchase Orders ────────────────────────────────────────
CREATE TABLE PURCHASE_ORDERS (
    PO_ID                   VARCHAR2(36)    PRIMARY KEY,
    PO_NUMBER               VARCHAR2(50)    NOT NULL UNIQUE,
    SUPPLIER_ID             VARCHAR2(36)    NOT NULL,
    WAREHOUSE_ID            VARCHAR2(36)    NOT NULL,
    CREATED_BY              VARCHAR2(36)    NOT NULL,
    APPROVED_BY             VARCHAR2(36),
    STATUS                  VARCHAR2(20)    DEFAULT 'DRAFT'
                            CHECK(STATUS IN ('DRAFT','APPROVED','ORDERED','DELIVERED','CANCELLED')),
    TOTAL_AMOUNT            NUMBER(14,2)    DEFAULT 0,
    EXPECTED_DELIVERY_DATE  DATE            NOT NULL,
    ACTUAL_DELIVERY_DATE    DATE,
    NOTES                   VARCHAR2(500),
    CREATED_AT              DATE            DEFAULT SYSDATE,
    UPDATED_AT              DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_PO_SUP FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT FK_PO_WH FOREIGN KEY(WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT FK_PO_CREATOR FOREIGN KEY(CREATED_BY) REFERENCES USERS(USER_ID)
);
CREATE INDEX IDX_PO_STATUS ON PURCHASE_ORDERS(STATUS);
CREATE INDEX IDX_PO_SUP ON PURCHASE_ORDERS(SUPPLIER_ID);
CREATE INDEX IDX_PO_DATE ON PURCHASE_ORDERS(CREATED_AT);

-- ── Purchase Order Items ───────────────────────────────────
CREATE TABLE PURCHASE_ORDER_ITEMS (
    ITEM_ID             VARCHAR2(36)    PRIMARY KEY,
    PO_ID               VARCHAR2(36)    NOT NULL,
    PRODUCT_ID          VARCHAR2(36)    NOT NULL,
    QUANTITY            NUMBER          NOT NULL CHECK(QUANTITY > 0),
    UNIT_PRICE          NUMBER(14,2)    NOT NULL,
    TOTAL_PRICE         NUMBER(14,2)    NOT NULL,
    RECEIVED_QUANTITY   NUMBER          DEFAULT 0,
    CONSTRAINT FK_POI_PO FOREIGN KEY(PO_ID) REFERENCES PURCHASE_ORDERS(PO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_POI_PROD FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);
CREATE INDEX IDX_POI_PO ON PURCHASE_ORDER_ITEMS(PO_ID);
CREATE INDEX IDX_POI_PROD ON PURCHASE_ORDER_ITEMS(PRODUCT_ID);

-- ── Stock Movements ────────────────────────────────────────
CREATE TABLE STOCK_MOVEMENTS (
    MOVEMENT_ID         VARCHAR2(36)    PRIMARY KEY,
    PRODUCT_ID          VARCHAR2(36)    NOT NULL,
    WAREHOUSE_ID        VARCHAR2(36)    NOT NULL,
    MOVEMENT_TYPE       VARCHAR2(20)    NOT NULL
                        CHECK(MOVEMENT_TYPE IN ('IN','OUT','TRANSFER','ADJUSTMENT')),
    QUANTITY            NUMBER          NOT NULL CHECK(QUANTITY > 0),
    FROM_WAREHOUSE_ID   VARCHAR2(36),
    TO_WAREHOUSE_ID     VARCHAR2(36),
    PURCHASE_ORDER_ID   VARCHAR2(36),
    BATCH_NUMBER        VARCHAR2(100),
    EXPIRY_DATE         DATE,
    UNIT_COST           NUMBER(14,2),
    PERFORMED_BY        VARCHAR2(36)    NOT NULL,
    REMARKS             VARCHAR2(500),
    WAS_BARCODE_SCAN    NUMBER(1)       DEFAULT 0,
    CREATED_AT          DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_SM_PROD FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_SM_WH FOREIGN KEY(WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT FK_SM_USER FOREIGN KEY(PERFORMED_BY) REFERENCES USERS(USER_ID)
);
CREATE INDEX IDX_SM_PROD ON STOCK_MOVEMENTS(PRODUCT_ID);
CREATE INDEX IDX_SM_WH ON STOCK_MOVEMENTS(WAREHOUSE_ID);
CREATE INDEX IDX_SM_TYPE ON STOCK_MOVEMENTS(MOVEMENT_TYPE);
CREATE INDEX IDX_SM_DATE ON STOCK_MOVEMENTS(CREATED_AT);

-- ── Forecasts ──────────────────────────────────────────────
CREATE TABLE FORECASTS (
    FORECAST_ID         VARCHAR2(36)    PRIMARY KEY,
    PRODUCT_ID          VARCHAR2(36)    NOT NULL,
    MODEL               VARCHAR2(30)    NOT NULL,
    PERIOD_LABEL        VARCHAR2(50)    NOT NULL,
    PERIOD_NUMBER       NUMBER          NOT NULL,
    PREDICTED_DEMAND    NUMBER(12,2)    NOT NULL,
    UPPER_BOUND         NUMBER(12,2)    NOT NULL,
    LOWER_BOUND         NUMBER(12,2)    NOT NULL,
    REORDER_SUGGESTION  NUMBER          DEFAULT 0,
    SAFETY_STOCK        NUMBER          DEFAULT 0,
    ACCURACY            NUMBER(5,2)     DEFAULT 0,
    GENERATED_AT        DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_FCST_PROD FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);
CREATE INDEX IDX_FCST_PROD ON FORECASTS(PRODUCT_ID);
CREATE INDEX IDX_FCST_DATE ON FORECASTS(GENERATED_AT);

-- ── Notifications ──────────────────────────────────────────
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID     VARCHAR2(36)    PRIMARY KEY,
    USER_ID             VARCHAR2(36)    NOT NULL,
    TYPE                VARCHAR2(50)    NOT NULL,
    TITLE               VARCHAR2(200)   NOT NULL,
    MESSAGE             VARCHAR2(1000)  NOT NULL,
    ENTITY_TYPE         VARCHAR2(50),
    ENTITY_ID           VARCHAR2(36),
    IS_READ             NUMBER(1)       DEFAULT 0,
    SEVERITY            VARCHAR2(20)    DEFAULT 'LOW'
                        CHECK(SEVERITY IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CREATED_AT          DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_NOTIF_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
CREATE INDEX IDX_NOTIF_USER ON NOTIFICATIONS(USER_ID);
CREATE INDEX IDX_NOTIF_READ ON NOTIFICATIONS(IS_READ);
CREATE INDEX IDX_NOTIF_DATE ON NOTIFICATIONS(CREATED_AT);

-- ── Audit Logs ─────────────────────────────────────────────
CREATE TABLE AUDIT_LOGS (
    LOG_ID          VARCHAR2(36)    PRIMARY KEY,
    USER_ID         VARCHAR2(36),
    ACTION          VARCHAR2(100)   NOT NULL,
    ENTITY_TYPE     VARCHAR2(50)    NOT NULL,
    ENTITY_ID       VARCHAR2(36),
    OLD_VALUES      CLOB,
    NEW_VALUES      CLOB,
    IP_ADDRESS      VARCHAR2(50),
    USER_AGENT      VARCHAR2(500),
    STATUS          VARCHAR2(20)    DEFAULT 'SUCCESS',
    ERROR_MESSAGE   VARCHAR2(500),
    CREATED_AT      DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);
CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOGS(ACTION);
CREATE INDEX IDX_AUDIT_DATE ON AUDIT_LOGS(CREATED_AT);
CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOGS(ENTITY_TYPE, ENTITY_ID);

-- ── Triggers ───────────────────────────────────────────────
-- Auto update UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATED_AT
BEFORE UPDATE ON USERS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTS_UPDATED_AT
BEFORE UPDATE ON PRODUCTS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/

CREATE OR REPLACE TRIGGER TRG_WAREHOUSES_UPDATED_AT
BEFORE UPDATE ON WAREHOUSES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/

CREATE OR REPLACE TRIGGER TRG_SUPPLIERS_UPDATED_AT
BEFORE UPDATE ON SUPPLIERS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/

-- ── Seed Data ──────────────────────────────────────────────
-- Admin user (password: Admin@123)
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, IS_ACTIVE)
VALUES ('admin-000-000-000-001', 'System Administrator', 'admin@inventrack.com',
'$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMqJqhCanROuH14j1nMRpUg30.', 'ADMIN', 1);

-- Manager user (password: Manager@123)
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, IS_ACTIVE)
VALUES ('mgr-000-000-000-001', 'Warehouse Manager', 'manager@inventrack.com',
'$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMqJqhCanROuH14j1nMRpUg30.', 'MANAGER', 1);

INSERT INTO WAREHOUSES (WAREHOUSE_ID, NAME, ADDRESS, CITY, STATE, COUNTRY, CONTACT_PERSON, CONTACT_PHONE, CAPACITY)
VALUES ('wh-001', 'Mumbai Central', 'Plot 12, MIDC Industrial Area', 'Mumbai', 'Maharashtra', 'India', 'Rajesh Kumar', '+91 9876543210', 10000);

INSERT INTO WAREHOUSES (WAREHOUSE_ID, NAME, ADDRESS, CITY, STATE, COUNTRY, CONTACT_PERSON, CONTACT_PHONE, CAPACITY)
VALUES ('wh-002', 'Delhi North', 'Sector 63, Noida', 'Delhi', 'Delhi', 'India', 'Priya Sharma', '+91 9876543211', 8000);

INSERT INTO SUPPLIERS (SUPPLIER_ID, NAME, CONTACT_PERSON, PHONE, EMAIL, ADDRESS, CITY, STATE, COUNTRY, LEAD_TIME_DAYS, RATING)
VALUES ('sup-001', 'TechParts India Pvt Ltd', 'Amit Verma', '+91 9000111222', 'sales@techparts.in', '45 Industrial Zone', 'Pune', 'Maharashtra', 'India', 7, 4.2);

INSERT INTO SUPPLIERS (SUPPLIER_ID, NAME, CONTACT_PERSON, PHONE, EMAIL, ADDRESS, CITY, STATE, COUNTRY, LEAD_TIME_DAYS, RATING)
VALUES ('sup-002', 'Global Electronics Corp', 'Sarah Johnson', '+1 555-0100', 'orders@globalelec.com', '200 Tech Park', 'Bangalore', 'Karnataka', 'India', 14, 4.5);

COMMIT;
