CREATE TABLE PURCHASE_ORDERS (
    PURCHASE_ORDER_ID NUMBER PRIMARY KEY,
    SUPPLIER_ID NUMBER,
    ORDER_DATE DATE DEFAULT SYSDATE,
    EXPECTED_DELIVERY DATE,
    STATUS VARCHAR2(50),

    FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIERS(SUPPLIER_ID)
);