CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    ORDER_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(50),
    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY(USER_ID)
    REFERENCES USERS(USER_ID)
);