CREATE TABLE AUDIT_LOGS (
    LOG_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    ACTION VARCHAR2(200),
    ACTION_DATE DATE DEFAULT SYSDATE,

    FOREIGN KEY(USER_ID)
    REFERENCES USERS(USER_ID)
);