CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID NUMBER PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(200),
    MANAGER_NAME VARCHAR2(100),
    CONTACT_NUMBER VARCHAR2(20),
    CREATED_AT DATE DEFAULT SYSDATE
);