CREATE TABLE PURCHASE_ORDER_ITEMS (
    PURCHASE_ITEM_ID NUMBER PRIMARY KEY,
    PURCHASE_ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    COST_PRICE NUMBER(12,2),

    FOREIGN KEY(PURCHASE_ORDER_ID)
    REFERENCES PURCHASE_ORDERS(PURCHASE_ORDER_ID),

    FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID)
);