CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(150) NOT NULL,
    EMAIL VARCHAR2(150),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(300),
    CITY VARCHAR2(100),
    COUNTRY VARCHAR2(100),
    RATING NUMBER(2,1),
    CREATED_AT DATE DEFAULT SYSDATE
);