CREATE TABLE SHIPMENTS (
    SHIPMENT_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    SHIPMENT_DATE DATE,
    DELIVERY_DATE DATE,
    STATUS VARCHAR2(50),
    TRACKING_NUMBER VARCHAR2(100),

    FOREIGN KEY(ORDER_ID)
    REFERENCES ORDERS(ORDER_ID)
);