CREATE TABLE PRODUCT_SUPPLIERS (
    PRODUCT_ID NUMBER,
    SUPPLIER_ID NUMBER,

    PRIMARY KEY(PRODUCT_ID,SUPPLIER_ID),

    FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID),

    FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIERS(SUPPLIER_ID)
);