CREATE TABLE DEMAND_FORECASTS (
    FORECAST_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    FORECAST_MONTH VARCHAR2(20),
    PREDICTED_DEMAND NUMBER,
    GENERATED_ON DATE DEFAULT SYSDATE,

    FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID)
);