CREATE TABLE INVENTORY_ALERTS (
    ALERT_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    ALERT_TYPE VARCHAR2(50),
    MESSAGE VARCHAR2(300),
    ALERT_DATE DATE DEFAULT SYSDATE,

    FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID)
);