CREATE OR REPLACE TRIGGER TRG_STOCK_UPDATE
AFTER INSERT ON STOCK_MOVEMENTS
FOR EACH ROW
BEGIN

   IF :NEW.MOVEMENT_TYPE='IN' THEN

      UPDATE PRODUCTS
      SET STOCK_QTY = STOCK_QTY + :NEW.QUANTITY
      WHERE PRODUCT_ID=:NEW.PRODUCT_ID;

   ELSIF :NEW.MOVEMENT_TYPE='OUT' THEN

      UPDATE PRODUCTS
      SET STOCK_QTY = STOCK_QTY - :NEW.QUANTITY
      WHERE PRODUCT_ID=:NEW.PRODUCT_ID;

   END IF;

END;
/