CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER NOT NULL,
    UNIT_PRICE NUMBER(12,2),

    FOREIGN KEY(ORDER_ID)
    REFERENCES ORDERS(ORDER_ID),

    FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID)
);