CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    PHONE VARCHAR2(20),
    ROLE VARCHAR2(20) CHECK (ROLE IN ('ADMIN','USER')),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT DATE DEFAULT SYSDATE
);