CREATE TABLE STOCK_MOVEMENTS (
    MOVEMENT_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    MOVEMENT_TYPE VARCHAR2(20)
    CHECK(MOVEMENT_TYPE IN ('IN','OUT')),

    QUANTITY NUMBER,
    MOVEMENT_DATE DATE DEFAULT SYSDATE,
    REMARKS VARCHAR2(300),

    FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID)
);