CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(200) NOT NULL,
    CATEGORY_ID NUMBER,
    SKU VARCHAR2(100) UNIQUE,
    BARCODE VARCHAR2(100) UNIQUE,
    DESCRIPTION VARCHAR2(500),
    UNIT_PRICE NUMBER(12,2),
    STOCK_QTY NUMBER DEFAULT 0,
    REORDER_LEVEL NUMBER DEFAULT 10,
    WAREHOUSE_ID NUMBER,
    CREATED_AT DATE DEFAULT SYSDATE,

    CONSTRAINT FK_PRODUCT_CATEGORY
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID),

    CONSTRAINT FK_PRODUCT_WAREHOUSE
    FOREIGN KEY (WAREHOUSE_ID)
    REFERENCES WAREHOUSES(WAREHOUSE_ID)
);