-- ============================================================
-- InvenTrack Pro -- SAMPLE DATA
-- Oracle SQL*Plus Compatible
-- Run AFTER schema.sql
-- ============================================================

-- PRODUCT CATEGORIES
INSERT INTO PRODUCT_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Electronics', 'Electronic devices and accessories');
INSERT INTO PRODUCT_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Clothing', 'Apparel and fashion items');
INSERT INTO PRODUCT_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Food & Beverage', 'Edible goods and beverages');
INSERT INTO PRODUCT_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Machinery', 'Industrial machinery and parts');
INSERT INTO PRODUCT_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Furniture', 'Office and home furniture');
INSERT INTO PRODUCT_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Office Supplies', 'Stationery and office essentials');

-- WAREHOUSES
INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION, MANAGER_NAME, CONTACT_NUMBER) VALUES (WAREHOUSE_SEQ.NEXTVAL, 'WH-Delhi Central', 'New Delhi, DL', 'Rajesh Kumar', '9810012345');
INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION, MANAGER_NAME, CONTACT_NUMBER) VALUES (WAREHOUSE_SEQ.NEXTVAL, 'WH-Mumbai West', 'Mumbai, MH', 'Priya Mehta', '9820023456');
INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION, MANAGER_NAME, CONTACT_NUMBER) VALUES (WAREHOUSE_SEQ.NEXTVAL, 'WH-Bangalore Tech', 'Bangalore, KA', 'Amit Sharma', '9830034567');
INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION, MANAGER_NAME, CONTACT_NUMBER) VALUES (WAREHOUSE_SEQ.NEXTVAL, 'WH-Chennai South', 'Chennai, TN', 'Deepa Rajan', '9840045678');

-- USERS
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, STATUS) VALUES (USER_SEQ.NEXTVAL, 'System Administrator', 'admin@inventrack.com', 'hashed_Admin123!', 'ADMIN', 'ACTIVE');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, STATUS) VALUES (USER_SEQ.NEXTVAL, 'Rajesh Kumar', 'rajesh.kumar@inventrack.com', 'hashed_Pass456!', 'WAREHOUSE_MANAGER', 'ACTIVE');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, STATUS) VALUES (USER_SEQ.NEXTVAL, 'Priya Mehta', 'priya.mehta@inventrack.com', 'hashed_Pass789!', 'INVENTORY_EXEC', 'ACTIVE');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, STATUS) VALUES (USER_SEQ.NEXTVAL, 'Amit Sharma', 'amit.sharma@customer.com', 'hashed_Cust001!', 'CUSTOMER', 'ACTIVE');

-- SUPPLIERS
INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, EMAIL, PHONE, CITY, COUNTRY, RATING) VALUES (SUPPLIER_SEQ.NEXTVAL, 'TechSource Ltd', 'orders@techsource.com', '1-800-TECH-SRC', 'San Jose', 'USA', 4.7);
INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, EMAIL, PHONE, CITY, COUNTRY, RATING) VALUES (SUPPLIER_SEQ.NEXTVAL, 'GlobalSupply Co', 'supply@globalsupply.com', '+44-20-7123-4567', 'London', 'UK', 4.2);
INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, EMAIL, PHONE, CITY, COUNTRY, RATING) VALUES (SUPPLIER_SEQ.NEXTVAL, 'PrimeParts Inc', 'info@primeparts.in', '022-4567-8901', 'Mumbai', 'India', 4.5);
INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, EMAIL, PHONE, CITY, COUNTRY, RATING) VALUES (SUPPLIER_SEQ.NEXTVAL, 'SwiftLogistics', 'ops@swiftlogistics.in', '080-9876-5432', 'Bangalore', 'India', 3.8);

-- PRODUCTS
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, SKU, BARCODE, UNIT_PRICE, STOCK_QTY, REORDER_LEVEL, WAREHOUSE_ID)
VALUES (PRODUCT_SEQ.NEXTVAL, 'HP LaserJet Printer Pro', 1, 'HP-LJ-PRO-001', '8901234567890', 15499.00, 47, 10, 1);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, SKU, BARCODE, UNIT_PRICE, STOCK_QTY, REORDER_LEVEL, WAREHOUSE_ID)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Dell Monitor 27 inch 4K', 1, 'DL-MON-27-4K', '8901234567891', 28999.00, 23, 5, 1);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, SKU, BARCODE, UNIT_PRICE, STOCK_QTY, REORDER_LEVEL, WAREHOUSE_ID)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Wireless Keyboard Logitech MX', 1, 'LG-KB-MX-003', '8901234567892', 4599.00, 0, 15, 2);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, SKU, BARCODE, UNIT_PRICE, STOCK_QTY, REORDER_LEVEL, WAREHOUSE_ID)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Office Executive Chair', 5, 'OFC-CHR-EXC-001', '8901234567893', 12999.00, 8, 10, 2);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, SKU, BARCODE, UNIT_PRICE, STOCK_QTY, REORDER_LEVEL, WAREHOUSE_ID)
VALUES (PRODUCT_SEQ.NEXTVAL, 'HP Printer Ink Cartridge Black', 1, 'HP-INK-BLK-001', '8901234567894', 899.00, 2, 15, 1);

-- PURCHASE ORDERS
INSERT INTO PURCHASE_ORDERS (PURCHASE_ORDER_ID, SUPPLIER_ID, ORDER_DATE, EXPECTED_DELIVERY, STATUS, TOTAL_AMOUNT)
VALUES (PURCHASE_ORDER_SEQ.NEXTVAL, 1, SYSDATE - 10, SYSDATE + 5, 'APPROVED', 154990.00);
INSERT INTO PURCHASE_ORDERS (PURCHASE_ORDER_ID, SUPPLIER_ID, ORDER_DATE, EXPECTED_DELIVERY, STATUS, TOTAL_AMOUNT)
VALUES (PURCHASE_ORDER_SEQ.NEXTVAL, 2, SYSDATE - 3, SYSDATE + 7, 'PENDING', 89997.00);
INSERT INTO PURCHASE_ORDERS (PURCHASE_ORDER_ID, SUPPLIER_ID, ORDER_DATE, EXPECTED_DELIVERY, STATUS, TOTAL_AMOUNT)
VALUES (PURCHASE_ORDER_SEQ.NEXTVAL, 3, SYSDATE - 15, SYSDATE - 5, 'DELIVERED', 45990.00);

-- ORDERS
INSERT INTO ORDERS (ORDER_ID, USER_ID, ORDER_DATE, STATUS, TOTAL_AMOUNT) VALUES (ORDER_SEQ.NEXTVAL, 4, SYSDATE - 5, 'DELIVERED', 28999.00);
INSERT INTO ORDERS (ORDER_ID, USER_ID, ORDER_DATE, STATUS, TOTAL_AMOUNT) VALUES (ORDER_SEQ.NEXTVAL, 4, SYSDATE - 2, 'PROCESSING', 15499.00);
INSERT INTO ORDERS (ORDER_ID, USER_ID, ORDER_DATE, STATUS, TOTAL_AMOUNT) VALUES (ORDER_SEQ.NEXTVAL, 4, SYSDATE, 'PENDING', 4599.00);

-- ORDER ITEMS
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (ORDER_ITEM_SEQ.NEXTVAL, 1, 2, 1, 28999.00);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (ORDER_ITEM_SEQ.NEXTVAL, 2, 1, 1, 15499.00);
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (ORDER_ITEM_SEQ.NEXTVAL, 3, 3, 1, 4599.00);

-- STOCK MOVEMENTS
INSERT INTO STOCK_MOVEMENTS (MOVEMENT_ID, PRODUCT_ID, MOVEMENT_TYPE, QUANTITY, REMARKS) VALUES (STOCK_MOVEMENT_SEQ.NEXTVAL, 1, 'IN', 50, 'Initial stock receipt from TechSource');
INSERT INTO STOCK_MOVEMENTS (MOVEMENT_ID, PRODUCT_ID, MOVEMENT_TYPE, QUANTITY, REMARKS) VALUES (STOCK_MOVEMENT_SEQ.NEXTVAL, 1, 'OUT', 3, 'Customer orders fulfilled');
INSERT INTO STOCK_MOVEMENTS (MOVEMENT_ID, PRODUCT_ID, MOVEMENT_TYPE, QUANTITY, REMARKS) VALUES (STOCK_MOVEMENT_SEQ.NEXTVAL, 2, 'IN', 25, 'PO-2024-001 received');
INSERT INTO STOCK_MOVEMENTS (MOVEMENT_ID, PRODUCT_ID, MOVEMENT_TYPE, QUANTITY, REMARKS) VALUES (STOCK_MOVEMENT_SEQ.NEXTVAL, 2, 'OUT', 2, 'Sale to customer');

-- DEMAND FORECASTS
INSERT INTO DEMAND_FORECASTS (FORECAST_ID, PRODUCT_ID, FORECAST_MONTH, PREDICTED_DEMAND, LOWER_BOUND, UPPER_BOUND, MODEL_USED)
VALUES (FORECAST_SEQ.NEXTVAL, 1, '2025-07', 45, 38, 52, 'xgboost');
INSERT INTO DEMAND_FORECASTS (FORECAST_ID, PRODUCT_ID, FORECAST_MONTH, PREDICTED_DEMAND, LOWER_BOUND, UPPER_BOUND, MODEL_USED)
VALUES (FORECAST_SEQ.NEXTVAL, 1, '2025-08', 48, 41, 56, 'xgboost');
INSERT INTO DEMAND_FORECASTS (FORECAST_ID, PRODUCT_ID, FORECAST_MONTH, PREDICTED_DEMAND, LOWER_BOUND, UPPER_BOUND, MODEL_USED)
VALUES (FORECAST_SEQ.NEXTVAL, 2, '2025-07', 22, 18, 26, 'prophet');

COMMIT;
-- End of sample_data.sql
