-- ============================================================
-- InvenTrack Pro -- Enterprise Inventory Management System
-- MASTER SCHEMA SCRIPT (Consolidated)
-- Oracle SQL*Plus Compatible
-- Execute in order: Sequences -> Tables -> Triggers -> Views
-- ============================================================

-- SECTION 1: SEQUENCES
CREATE SEQUENCE USER_SEQ          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCT_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE WAREHOUSE_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SUPPLIER_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDER_SEQ         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDER_ITEM_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE STOCK_MOVEMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CATEGORY_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PURCHASE_ORDER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE INVENTORY_ALERT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- SECTION 2: BASE TABLES
CREATE TABLE PRODUCT_CATEGORIES (
    CATEGORY_ID   NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION   VARCHAR2(300),
    CREATED_AT    DATE DEFAULT SYSDATE
);

CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID   NUMBER PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR2(100) NOT NULL,
    LOCATION       VARCHAR2(200),
    MANAGER_NAME   VARCHAR2(100),
    CONTACT_NUMBER VARCHAR2(20),
    CAPACITY       NUMBER DEFAULT 10000,
    CURRENT_STOCK  NUMBER DEFAULT 0,
    STATUS         VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT     DATE DEFAULT SYSDATE
);

CREATE TABLE USERS (
    USER_ID       NUMBER PRIMARY KEY,
    FULL_NAME     VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    PHONE         VARCHAR2(20),
    ROLE          VARCHAR2(30) CHECK (ROLE IN ('ADMIN','WAREHOUSE_MANAGER','SUPPLIER','INVENTORY_EXEC','CUSTOMER')),
    STATUS        VARCHAR2(20) DEFAULT 'ACTIVE',
    LAST_LOGIN    DATE,
    CREATED_AT    DATE DEFAULT SYSDATE
);

CREATE TABLE SUPPLIERS (
    SUPPLIER_ID   NUMBER PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(150) NOT NULL,
    EMAIL         VARCHAR2(150),
    PHONE         VARCHAR2(20),
    ADDRESS       VARCHAR2(300),
    CITY          VARCHAR2(100),
    COUNTRY       VARCHAR2(100),
    RATING        NUMBER(2,1),
    STATUS        VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT    DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_SUPPLIER_RATING CHECK (RATING BETWEEN 0 AND 5)
);

-- SECTION 3: DEPENDENT TABLES
CREATE TABLE PRODUCTS (
    PRODUCT_ID    NUMBER PRIMARY KEY,
    PRODUCT_NAME  VARCHAR2(200) NOT NULL,
    CATEGORY_ID   NUMBER,
    SKU           VARCHAR2(100) UNIQUE,
    BARCODE       VARCHAR2(100) UNIQUE,
    DESCRIPTION   VARCHAR2(500),
    UNIT_PRICE    NUMBER(12,2),
    STOCK_QTY     NUMBER DEFAULT 0,
    REORDER_LEVEL NUMBER DEFAULT 10,
    WAREHOUSE_ID  NUMBER,
    CREATED_AT    DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PRODUCT_CATEGORY  FOREIGN KEY (CATEGORY_ID)  REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_PRODUCT_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT CHK_STOCK_QTY        CHECK (STOCK_QTY >= 0)
);

CREATE TABLE PRODUCT_SUPPLIERS (
    PRODUCT_ID    NUMBER NOT NULL,
    SUPPLIER_ID   NUMBER NOT NULL,
    UNIT_COST     NUMBER(12,2),
    LEAD_DAYS     NUMBER DEFAULT 7,
    IS_PRIMARY    VARCHAR2(1) DEFAULT 'N',
    CREATED_AT    DATE DEFAULT SYSDATE,
    PRIMARY KEY (PRODUCT_ID, SUPPLIER_ID),
    CONSTRAINT FK_PS_PRODUCT  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_PS_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);

CREATE TABLE PURCHASE_ORDERS (
    PURCHASE_ORDER_ID NUMBER PRIMARY KEY,
    SUPPLIER_ID       NUMBER,
    ORDER_DATE        DATE DEFAULT SYSDATE,
    EXPECTED_DELIVERY DATE,
    ACTUAL_DELIVERY   DATE,
    STATUS            VARCHAR2(50) DEFAULT 'DRAFT',
    TOTAL_AMOUNT      NUMBER(14,2),
    NOTES             VARCHAR2(500),
    CONSTRAINT FK_PO_SUPPLIER  FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT CHK_PO_STATUS   CHECK (STATUS IN ('DRAFT','PENDING','APPROVED','IN_TRANSIT','DELIVERED','CANCELLED'))
);

CREATE TABLE PURCHASE_ORDER_ITEMS (
    ITEM_ID           NUMBER PRIMARY KEY,
    PURCHASE_ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID        NUMBER NOT NULL,
    QUANTITY          NUMBER NOT NULL,
    UNIT_PRICE        NUMBER(12,2),
    RECEIVED_QTY      NUMBER DEFAULT 0,
    CONSTRAINT FK_POI_PO      FOREIGN KEY (PURCHASE_ORDER_ID) REFERENCES PURCHASE_ORDERS(PURCHASE_ORDER_ID),
    CONSTRAINT FK_POI_PRODUCT FOREIGN KEY (PRODUCT_ID)        REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID     NUMBER PRIMARY KEY,
    USER_ID      NUMBER,
    ORDER_DATE   DATE DEFAULT SYSDATE,
    STATUS       VARCHAR2(50) DEFAULT 'PENDING',
    TOTAL_AMOUNT NUMBER(12,2),
    NOTES        VARCHAR2(500),
    CONSTRAINT FK_ORDER_USER    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT CHK_ORDER_STATUS CHECK (STATUS IN ('PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURNED'))
);

CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER PRIMARY KEY,
    ORDER_ID      NUMBER NOT NULL,
    PRODUCT_ID    NUMBER NOT NULL,
    QUANTITY      NUMBER NOT NULL,
    UNIT_PRICE    NUMBER(12,2),
    CONSTRAINT FK_OI_ORDER   FOREIGN KEY (ORDER_ID)   REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_OI_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE SHIPMENTS (
    SHIPMENT_ID      NUMBER PRIMARY KEY,
    ORDER_ID         NUMBER NOT NULL,
    SHIPMENT_DATE    DATE,
    DELIVERY_DATE    DATE,
    STATUS           VARCHAR2(50) DEFAULT 'PENDING',
    TRACKING_NUMBER  VARCHAR2(100),
    CARRIER          VARCHAR2(100),
    CONSTRAINT FK_SHIP_ORDER  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE STOCK_MOVEMENTS (
    MOVEMENT_ID   NUMBER PRIMARY KEY,
    PRODUCT_ID    NUMBER NOT NULL,
    MOVEMENT_TYPE VARCHAR2(20) NOT NULL CHECK (MOVEMENT_TYPE IN ('IN','OUT','ADJUSTMENT')),
    QUANTITY      NUMBER NOT NULL,
    MOVEMENT_DATE DATE DEFAULT SYSDATE,
    WAREHOUSE_ID  NUMBER,
    REMARKS       VARCHAR2(300),
    CONSTRAINT FK_SM_PRODUCT   FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_SM_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

CREATE TABLE STOCK_TRANSFERS (
    TRANSFER_ID    NUMBER PRIMARY KEY,
    FROM_WAREHOUSE NUMBER NOT NULL,
    TO_WAREHOUSE   NUMBER NOT NULL,
    PRODUCT_ID     NUMBER NOT NULL,
    QUANTITY       NUMBER NOT NULL,
    TRANSFER_DATE  DATE DEFAULT SYSDATE,
    STATUS         VARCHAR2(50) DEFAULT 'PENDING',
    CONSTRAINT FK_ST_FROM_WH FOREIGN KEY (FROM_WAREHOUSE) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT FK_ST_TO_WH   FOREIGN KEY (TO_WAREHOUSE)   REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT FK_ST_PRODUCT FOREIGN KEY (PRODUCT_ID)     REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE INVENTORY_ALERTS (
    ALERT_ID   NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    ALERT_TYPE VARCHAR2(50) NOT NULL,
    MESSAGE    VARCHAR2(300),
    SEVERITY   VARCHAR2(20) DEFAULT 'WARNING',
    IS_READ    VARCHAR2(1) DEFAULT 'N',
    ALERT_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_IA_PRODUCT  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT CHK_IA_TYPE    CHECK (ALERT_TYPE IN ('LOW STOCK','STOCKOUT','OVERSTOCK','EXPIRY','DELAYED'))
);

CREATE TABLE DEMAND_FORECASTS (
    FORECAST_ID      NUMBER PRIMARY KEY,
    PRODUCT_ID       NUMBER NOT NULL,
    FORECAST_MONTH   VARCHAR2(20) NOT NULL,
    PREDICTED_DEMAND NUMBER,
    LOWER_BOUND      NUMBER,
    UPPER_BOUND      NUMBER,
    MODEL_USED       VARCHAR2(30),
    GENERATED_ON     DATE DEFAULT SYSDATE,
    CONSTRAINT FK_DF_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE AUDIT_LOGS (
    LOG_ID      NUMBER PRIMARY KEY,
    USER_ID     NUMBER,
    TABLE_NAME  VARCHAR2(50),
    ACTION      VARCHAR2(200) NOT NULL,
    OLD_VALUE   VARCHAR2(1000),
    NEW_VALUE   VARCHAR2(1000),
    ACTION_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_AL_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- SECTION 4: INDEXES
CREATE INDEX IDX_PRODUCT_CATEGORY  ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IDX_PRODUCT_WAREHOUSE ON PRODUCTS(WAREHOUSE_ID);
CREATE INDEX IDX_ORDERS_USER       ON ORDERS(USER_ID);
CREATE INDEX IDX_ORDERS_STATUS     ON ORDERS(STATUS);
CREATE INDEX IDX_SM_PRODUCT        ON STOCK_MOVEMENTS(PRODUCT_ID);
CREATE INDEX IDX_IA_PRODUCT        ON INVENTORY_ALERTS(PRODUCT_ID);
CREATE INDEX IDX_AL_DATE           ON AUDIT_LOGS(ACTION_DATE);

-- SECTION 5: TRIGGERS
CREATE OR REPLACE TRIGGER TRG_STOCK_UPDATE
AFTER INSERT ON STOCK_MOVEMENTS
FOR EACH ROW
BEGIN
    IF :NEW.MOVEMENT_TYPE = 'IN' THEN
        UPDATE PRODUCTS SET STOCK_QTY = STOCK_QTY + :NEW.QUANTITY WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
    ELSIF :NEW.MOVEMENT_TYPE = 'OUT' THEN
        UPDATE PRODUCTS SET STOCK_QTY = STOCK_QTY - :NEW.QUANTITY WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOW_STOCK
AFTER UPDATE OF STOCK_QTY ON PRODUCTS
FOR EACH ROW
WHEN (NEW.STOCK_QTY < NEW.REORDER_LEVEL)
BEGIN
    INSERT INTO INVENTORY_ALERTS (ALERT_ID, PRODUCT_ID, ALERT_TYPE, MESSAGE, SEVERITY, ALERT_DATE)
    VALUES (INVENTORY_ALERT_SEQ.NEXTVAL, :NEW.PRODUCT_ID, 'LOW STOCK',
            'Stock below reorder level',
            CASE WHEN :NEW.STOCK_QTY = 0 THEN 'CRITICAL' ELSE 'WARNING' END, SYSDATE);
END;
/

-- SECTION 6: VIEWS
CREATE OR REPLACE VIEW INVENTORY_SUMMARY AS
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.SKU, P.STOCK_QTY, P.REORDER_LEVEL,
       P.UNIT_PRICE, PC.CATEGORY_NAME, W.WAREHOUSE_NAME,
       CASE WHEN P.STOCK_QTY = 0 THEN 'OUT_OF_STOCK'
            WHEN P.STOCK_QTY < P.REORDER_LEVEL THEN 'LOW_STOCK'
            ELSE 'OK' END AS STOCK_STATUS
FROM PRODUCTS P
LEFT JOIN PRODUCT_CATEGORIES PC ON P.CATEGORY_ID = PC.CATEGORY_ID
LEFT JOIN WAREHOUSES W ON P.WAREHOUSE_ID = W.WAREHOUSE_ID;

CREATE OR REPLACE VIEW SUPPLIER_PERFORMANCE_VIEW AS
SELECT S.SUPPLIER_ID, S.SUPPLIER_NAME, S.RATING,
       COUNT(PO.PURCHASE_ORDER_ID) AS TOTAL_ORDERS,
       SUM(CASE WHEN PO.STATUS = 'DELIVERED' THEN 1 ELSE 0 END) AS DELIVERED,
       ROUND(SUM(CASE WHEN PO.STATUS = 'DELIVERED' THEN 1 ELSE 0 END) * 100.0
             / NULLIF(COUNT(PO.PURCHASE_ORDER_ID), 0), 2) AS DELIVERY_RATE_PCT
FROM SUPPLIERS S LEFT JOIN PURCHASE_ORDERS PO ON S.SUPPLIER_ID = PO.SUPPLIER_ID
GROUP BY S.SUPPLIER_ID, S.SUPPLIER_NAME, S.RATING;

CREATE OR REPLACE VIEW SALES_ANALYTICS_VIEW AS
SELECT TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS SALES_MONTH,
       COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
       SUM(CASE WHEN O.STATUS = 'DELIVERED' THEN O.TOTAL_AMOUNT ELSE 0 END) AS MONTHLY_REVENUE,
       COUNT(DISTINCT O.USER_ID) AS UNIQUE_CUSTOMERS
FROM ORDERS O
GROUP BY TO_CHAR(O.ORDER_DATE, 'YYYY-MM')
ORDER BY SALES_MONTH;

COMMIT;
