CREATE OR REPLACE TRIGGER LOW_STOCK_ALERT
AFTER UPDATE OF STOCK_QTY
ON PRODUCTS
FOR EACH ROW
WHEN (NEW.STOCK_QTY <= NEW.REORDER_LEVEL)

BEGIN

INSERT INTO INVENTORY_ALERTS
VALUES(
INVENTORY_ALERT_SEQ.NEXTVAL,
:NEW.PRODUCT_ID,
'LOW STOCK',
'Restock Required',
SYSDATE
);

END;
/