CREATE OR REPLACE VIEW INVENTORY_SUMMARY AS

SELECT
P.PRODUCT_ID,
P.PRODUCT_NAME,
P.STOCK_QTY,
P.REORDER_LEVEL,
W.WAREHOUSE_NAME

FROM PRODUCTS P
JOIN WAREHOUSES W

ON P.WAREHOUSE_ID = W.WAREHOUSE_ID;